##############################################################################
# Template generated by PrimeLib T-2022.03-SP1 (built on Apr 12, 2022 13:01:04) #
# PrimeLib Path: /proj/cad/synopsys/synopsys_2021/primelib/T-2022.03-SP1/linux64/bin/primelib #
# Host Name: engnx02a.utdallas.edu, User Name: sxv240035, PID: 32544 #
# Directory: /home/eng/s/sxv240035/cad/gf65/primelib_gf65 #
# Date Thu, 05 Dec 2024 22:00:51 CST #
#                                                                            #
# Copyright (C) 2022 Synopsys Inc.                                #
# This file contains confidential and proprietry information.                #
# All rights reserved.                                                       #
#                                                                            #
##############################################################################

set tempTestColl [ SBTestCollection automap ]


# Specifies the version of the template API expected by this file.
$tempTestColl setTemplateVer 7

## 
## Configuration Flags
$tempTestColl setConfigurationFlags { doTiming doPower }

## 
## Formal Ports
$tempTestColl makeFormalPorts {VSS D CLK Q R VDD}
$tempTestColl setParameter retention_ports {}
$tempTestColl setParameter synch_controls {}
$tempTestColl setParameter clock_ports {CLK}
$tempTestColl setParameter asynch_ports {R}
$tempTestColl setParameter asynch_ports_active_state {R 01 Q 10}

## 
## Tests

## 
## Test cmpw_hbm__R__lh__R__hl
set tempTest [ SBTest "cmpw_hbm__R__lh__R__hl" ]
$tempTest setTargets { cmpw_hbm__R__lh__R__hl }
$tempTest setTargetInputs {
  {R lh}}

$tempTest setTargetOutputs {
  {Q hl}}

$tempTest setTargetReferences {
  {R hl}}

$tempTest setSwitchingInputs {
  {R lh}}

$tempTest setSwitchingRefs {
  {R hl}}

$tempTest setAnalysisType tranPlus

## 
## Sweep Specification
$tempTest setTagNumTableDimensions 0 mpw

## 
## Harnesses
$tempTest setAcquire 1

## 
## ACQ_1
set tempAcq [ SBMPWHBMAcquisition "ACQ_1" ]
$tempAcq setHarnessName default
$tempAcq setAcquire 1
$tempAcq setState "!CLK&!D"
$tempAcq setStateCoverage "1"

## 
## Wavetable
set tempWT [ SBWaveTable ]
$tempWT setInterface { Q:out R D CLK } { initial_delay units ct default_slew stable cmpw min_cmpw max_cmpw opt_tolerance init_hbm degrade_cmpw }

$tempWT setStimulus                           {   R    D    CLK  Q     } {
                              "0"          {} {   0    0    0    1     }
                  "initial_delay" { in1 out } {   1    -    -    0     }
           "(initial_delay)+cmpw"     { in2 } {   0    -    -    -     }
"((initial_delay)+cmpw)+(stable)"          {} {   -    -    -    -     }
}

$tempWT addMeasurements {} {
  { tin_hbm_R            Tin_hbm    { R in1 } NO_USER SYS }
  { cmpw_hbm_R           cmpw_hbm   { R in1 R in2 } NO_USER SYS }
  { tout_hbm_Q           Tout_hbm   { Q in1 0 1 } NO_USER SYS }
  { delay_hbm_R_Q        delay_hbm  { R in1 Q in1 0 } NO_USER SYS }
  { fallback_hbm_Q       fallback_hbm { Q in1 0 } NO_USER SYS }
  { sis_pass_fail        passfail_hbm { 0 R R } NO_USER SYS }
}

$tempWT addHbm    cmpw    min_cmpw    max_cmpw    delay_hbm_R_Q    independent   { Q relative-degradation }   { Q positive-side }   { Q 0.1 -1 }   { Q 1e-11 1e-08 -1 }  { (fallback_hbm__Q__hl_trig-tout_hbm__Q__hl_targ) (fallback_hbm__Q__hl_targ-tout_hbm__Q__hl_trig) }   {  }  { Q hl }  {  }  { cmpw_hbm__R__lh__R__hl_trig cmpw_hbm__R__lh__R__hl_targ tin_hbm__R__lh_trig tin_hbm__R__lh_targ tout_hbm__Q__hl_trig tout_hbm__Q__hl_targ delay_hbm__R__lh__Q__hl_trig delay_hbm__R__lh__Q__hl_targ } {  } { relative Q delay_hbm__R__lh__Q__hl_value } { cmpw_hbm__R__lh__R__hl_value } {  } {  } expand None opt_tolerance None None max_cmpw "1"
$tempWT bindInterface { Q R D CLK } { 10e-12 R[cycle_time] R[cycle_time] R[default_slew] max(R[stable_time],Q[stable_time]) R[max_cmpw] R[min_cmpw] R[max_cmpw] R[constraint_resolution] R[min_cmpw] 0.0 }
$tempAcq addWaveTable $tempWT
release_obj $tempWT

## 
## Initialization Acquisition
$tempAcq setInitializationAcquisition initialization__ACQ_2

## 
## Sweep Specification
$tempAcq setTagNumTableDimensions 0 mpw

## 
## Harnesses

set tempHarness [ SBHarness default ]
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement capacitor
$tempTopOp setElementName cap_Q
$tempTopOp setOperation insert
$tempTopOp setNodes {Q Q[logic_low_name]}
$tempTopOp setParam {load_Q}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement capacitor
$tempTopOp setElementName cap_VSS
$tempTopOp setOperation insert
$tempTopOp setNodes {VSS VSS[logic_low_name]}
$tempTopOp setParam {load_VSS}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement capacitor
$tempTopOp setElementName cap_VDD
$tempTopOp setOperation insert
$tempTopOp setNodes {VDD VDD[logic_low_name]}
$tempTopOp setParam {load_VDD}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
$tempAcq addHarness $tempHarness
release_obj $tempHarness

$tempAcq setHarnessName default
$tempTest addAcquisition $tempAcq
release_obj $tempAcq

$tempTestColl addTest $tempTest
release_obj $tempTest

set tempTestColl

