##############################################################################
# Template generated by PrimeLib T-2022.03-SP1 (built on Apr 12, 2022 13:01:04) #
# PrimeLib Path: /proj/cad/synopsys/synopsys_2021/primelib/T-2022.03-SP1/linux64/bin/primelib #
# Host Name: engnx02a.utdallas.edu, User Name: sxv240035, PID: 21441 #
# Directory: /home/eng/s/sxv240035/cad/gf65/primelib_gf65 #
# Date Thu, 05 Dec 2024 22:35:59 CST #
#                                                                            #
# Copyright (C) 2022 Synopsys Inc.                                #
# This file contains confidential and proprietry information.                #
# All rights reserved.                                                       #
#                                                                            #
##############################################################################

set tempTestColl [ SBTestCollection automap ]


# Specifies the version of the template API expected by this file.
$tempTestColl setTemplateVer 7

## 
## Configuration Flags
$tempTestColl setConfigurationFlags { doTiming doPower }

## 
## Formal Ports
$tempTestColl makeFormalPorts {VDD OUT EN VSS IN}
$tempTestColl setParameter retention_ports {}
$tempTestColl setParameter synch_controls {}
$tempTestColl setParameter clock_ports {}
$tempTestColl setParameter asynch_ports {}
$tempTestColl setParameter asynch_ports_active_state {}

## 
## Tests

## 
## Test zen__EN__lh__OUT__lzh
set tempTest [ SBTest "zen__EN__lh__OUT__lzh" ]
$tempTest setTargets { zen__EN__lh__OUT__lzh Cin__EN__lh Tout__OUT__zh }
$tempTest setTargetInputs {
  {EN lh}}

$tempTest setTargetOutputs {
  {OUT lzh}}

$tempTest setSwitchingInputs {
  {EN lh}}

$tempTest setAnalysisType tranPlus

## 
## Sweep Specification
$tempTest setTagNumTableDimensions 0 mpw

## 
## Harnesses
$tempTest setAcquire 1

## 
## ACQ_1
set tempAcq [ SBZenAcquisition "ACQ_1" ]
$tempAcq setHarnessName default
$tempAcq setAcquire 1
$tempAcq setState "!IN"
$tempAcq setStateCoverage "1"

## 
## Wavetable
set tempWT [ SBWaveTable ]
$tempWT setInterface { EN IN OUT:inout } { initial_delay units ct default_slew ns volt_tolerance volt_resolution_threshold stable pp }

$tempWT setStimulus                                              {   EN   IN   OUT   } {
                                                 "0"          {} {   0    0    0,Z   }
                                     "initial_delay" { in1 out } {   1    -    Z,1   }
"max((initial_delay)+(stable),(initial_delay)+(pp))"          {} {   -    -    -,-   }
}

$tempWT addMeasurements {} {
  { tin_EN               Tin        { EN in1 } NO_USER SYS }
  { tout_OUT             Tout       { OUT out } NO_USER SYS }
  { vsample__OUT__out    vsample    { OUT out (initial_delay)+(stable) ns volt_tolerance 0 volt_resolution_threshold } NO_USER SYS }
  { zen_EN_OUT           zen        { EN in1 OUT out } NO_USER SYS }
  { cin_EN               Cin        { EN in1 } NO_USER SYS }
}

$tempWT bindInterface { EN IN OUT } { 10e-12 EN[cycle_time] EN[cycle_time] EN[default_slew] nsamples OUT[voltage_resolution] OUT[voltage_resolution_threshold] OUT[stable_time] cell_power_period }
$tempAcq addWaveTable $tempWT
release_obj $tempWT

## 
## Sweep Specification
$tempAcq setTagNumTableDimensions 0 mpw

## 
## Harnesses

set tempHarness [ SBHarness default ]
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement capacitor
$tempTopOp setElementName cap_OUT
$tempTopOp setOperation insert
$tempTopOp setNodes {OUT OUT[logic_low_name]}
$tempTopOp setParam {load_OUT}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement capacitor
$tempTopOp setElementName cap_VSS
$tempTopOp setOperation insert
$tempTopOp setNodes {VSS VSS[logic_low_name]}
$tempTopOp setParam {load_VSS}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
set tempTopOp [ SBTopologyOperation ]
$tempTopOp setElement capacitor
$tempTopOp setElementName cap_VDD
$tempTopOp setOperation insert
$tempTopOp setNodes {VDD VDD[logic_low_name]}
$tempTopOp setParam {load_VDD}
$tempHarness addTopologyOperation $tempTopOp
release_obj $tempTopOp
$tempAcq addHarness $tempHarness
release_obj $tempHarness

$tempAcq setHarnessName default
$tempTest addAcquisition $tempAcq
release_obj $tempAcq

$tempTestColl addTest $tempTest
release_obj $tempTest

set tempTestColl

